# Generated by Django 5.0.6 on 2024-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='file_upload',
            field=models.FileField(blank='false', upload_to='uploads/'),
        ),
    ]
